exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
fail_fast: false
# default_language_version:
#   python: python3.10
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-rewrite
default_stages: [pre-commit]

repos:
# ---------------------------------------------------------------------------- #
#                               Pre-Commit Hooks                             #
# ---------------------------------------------------------------------------- #

# -----------------------------  Security Tools ---------------------------- #
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: " security 路 Detect hardcoded secrets by detect-secrets"
        ## Generated by `detect-secrets scan > .secrets.baseline`
        args: ['--baseline', '.secrets.baseline']
        exclude: ^(tests|mock_data)/

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: " security 路 Detect hardcoded secrets by gitleaks"

# ---------------------------  Code Quality Tools -------------------------- #
  ### Markdown ###
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: " markdown 路 Format markdown via markdownlint-cli2"
        args: [--fix]

  - repo: local
    hooks:
      - id: check-vale-preset
        name: " shell 路 Check on exists vale preset"
        entry: |
          bash -c '.gitlab/scripts/vale-sync.sh'
        language: system

  - repo: https://github.com/errata-ai/vale
    rev: v3.12.0
    hooks:
      - id: vale
        name: " markdown 路 Lint markdown via vale"
        description: Run vale on your text
        entry: vale
        language: golang
        types: [text]
        args: [--minAlertLevel=error]

  ### Shell/Bash ###
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: " shell 路 Lint shell scripts"
        require_serial: true
        exclude: ^legacy/

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        name: " shell 路 Format shell scripts"
        args: [
          -i=2,
          -bn,
          -ci,
          -s,
          -w
        ]

      - id: shfmt
        name: " shell 路 Test shell scripts format"
        args: [
          -i=2,
          -bn,
          -ci,
          -s,
          -d
        ]

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: " shell 路 Check shell script code style"
        args: ['-i', 'E003,E010']

  ### Syntax ###
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: " codespell 路 Validate files for spelling errors"
        args: ['-I', '.codespell-exclude-words']
        additional_dependencies:
          - tomli

  ### Docker ###
  - repo: local
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        name: " docker 路 Lint Dockerfile"
        language: docker_image
        types: [file]
        files: ^Dockerfile.*

  # STRICT
  # - repo: https://github.com/AleksaC/hadolint-py
  #   rev: v2.12.1b3
  #   hooks:
  #     - id: hadolint
  #       name: " docker 路 Lint Dockerfile"
  #       args: ['Dockerfile']

  # STRICT
  # - repo: https://github.com/hadolint/hadolint.git
  #   rev: v2.13.1-beta
  #   hooks:
  #     - id: hadolint-docker
  #       name: " docker 路 Lint Dockerfile"
  #       args:
  #         [
  #           "--ignore=DL3008",
  #           "--ignore=DL3013",
  #           "--ignore=DL3018",
  #           "--ignore=DL3059",
  #         ]

  - repo: local
    hooks:
      - id: dclint
        name: " docker 路 Lint docker-compose file"
        entry: dclint .
        language: node
        require_serial: true
        pass_filenames: false
        additional_dependencies:
          - dclint@2.2.2

# ----------------------------  Filesystem Tools --------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Filesystem Checks
      - id: trailing-whitespace
        name: " filesystem/锔 whitespaces 路 Verify shebang presence"
      - id: end-of-file-fixer
        name: " filesystem/锔 eof 路 Makes sure files end in a newline and only a newline"
      - id: detect-private-key
        name: " filesystem/ security 路 Checks for the existence of private keys"
      - id: check-executables-have-shebangs
        name: " filesystem/锔 exec 路 Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: " filesystem/锔 exec 路 Verify script permissions"
      - id: check-case-conflict
        name: " filesystem/ names 路 Check case sensitivity"
      - id: mixed-line-ending
        name: " filesystem/锔 line ending 路 Replaces or checks mixed line ending"
        args: [--fix=lf]
# -------------------------------  Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: " git 路 Detect conflict markers"
      - id: check-added-large-files
        name: " git 路 Block large file commits"
        args: [--maxkb=5120]

# ----------------------------  Selfcheck ---------------------------------- #
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: " pre-commit 路 Ensures that the configured hooks apply to at least one file in the repository"
      # STRICT
      # - id: check-useless-excludes
      #   name: " pre-commit 路 Ensures that exclude directives apply to any file in the repository"

# ---------------------------------------------------------------------------- #
#                             Commit Message Hooks                           #
# ---------------------------------------------------------------------------- #
#
# --------------------------- 锔 Git Commit Quality -------------------------- #
  - repo: local
    hooks:
      - id: custom-commit-parser
        name: " git 路 Validate commit message"
        entry: |
          bash -c '
            # MSG=$(git log -1 --pretty=%B);
            MSG_FILE="${1}";
            MSG=$(<"${MSG_FILE}");
            RE="^((Merge[ a-z-]* branch.*)|(Revert*)|((feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert)(\(.*\))?!?: .{10,}))";
            if ! [[ ${MSG} =~ ${RE} ]]; then
              echo >&2 "[POLICY] Invalid commit message format!";
              echo >&2 "[ERROR]: Commit message must follow Conventional Commits";
              echo >&2 "Message must follow the pattern: type(scope): description"
              echo >&2 "Allowed types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert";
              echo >&2 "Description must be min 10 chars";
              echo >&2 "Example: feat(auth): Add login button";
              exit 1;
            fi
          '
        args: ["COMMIT_EDITMSG"]
        language: system
        stages: [commit-msg, post-rewrite]

      - id: branch-name
        name: " git 路 Validate commit branch"
        entry: |
          bash -c '
            # BRANCH=$(git branch --show-current);
            BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "(detached)");
            if [[ "$BRANCH" == "(detached)" ]]; then
              echo >&2 "[POLICY] Cannot push from detached HEAD!";
              exit 1;
            fi

            RE="^(feature|fix|hotfix)/.{5,}|master|main|test|dev.*$";
            if ! [[ ${BRANCH} =~ ${RE} ]]; then
              echo >&2 "[POLICY] Invalid branch name format!";
              echo >&2 "[ERROR]: Branch name must follow in specific type";
              echo >&2 "Name after branch type must be min 5 chars";
              echo >&2 "Allowed types: feature, fix, hotfix";
              echo >&2 "Examples:";
              echo >&2 "hotfix/issue-[NUM]-desc";
              echo >&2 "feature/[JIRA-ID]-short-desc";
              echo >&2 "dev*|test|master|main";
              exit 1;
            fi
          '
        language: system
        stages: [pre-push]

# ---------------------------------------------------------------------------- #
#                             И Fast Tests (Local)                            #
# ---------------------------------------------------------------------------- #
  - repo: local
    hooks:
      - id: docker-tag-validator
        name: " docker 路 Validate Dockerfile for 'latest' tag"
        entry: |
          bash -c 'grep -q "latest" Dockerfile* && echo "[ERROR]: Do not use latest tag" && exit 1 || true'
        language: system

      - id: check-todos
        name: " shell 路 Check 'TODO/FIXME' on shell files"
        entry: |
          bash -c '! grep -rn "FIXME\|TODO" --include="*.sh" . || (echo "[ERROR]: Remove TODOs before commit!" && exit 1)'
        language: system

      - id: check-md5sum
        name: " shell 路 Check md5sum of main files"
        entry: |
          bash -c 'cat MD5SUM | md5sum -c - || (echo "[ERROR]: MD5SUM is not valid!" && exit 1)'
        language: system

      - id: auto-update-pre-commit
        name: " pre-commit 路 Auto-update pre-commit"
        entry: bash -c 'pre-commit autoupdate || true'
        language: system
        always_run: true

      - id: check-png-size
        name: " filesystem/ file 路 Check image size"
        # bash -c 'find . \( -name '*.png' -o -name '*.webp' -o -name '*.svg' -o -name '*.jpg' \) -size +500k -exec echo "[ERROR]: {} is too large" \; | grep '.' && exit 1 || true'
        entry: |
          bash -c 'git diff --cached --name-only | grep -Ei "\\.(png|webp|jpe?g)\$" | while read -r f; do size=$(wc -c < "${f}"); if [[ ${size} -gt 512000 ]]; then echo "[ERROR]: ${f} is too large (${size} bytes > 500KB)" >&2; exit 1; fi; done'
        language: system
